[project]
authors = [
    {name = "Nacef Guessaymi", email = "nacefguess@hotmail.com"}
]
description = "AqSolPred aqueous solubility prediction pipeline (CLI + web app)"
name = "aqsolpred_web"
version = "0.1.0"
readme = "README.md"
requires-python = "==3.7.6"

[project.scripts]
aqsolpred_predict = "aqsolpred_web.cli.predict:main"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["aqsolpred_web*"]
