"""Shared constants for the features package."""

from __future__ import annotations
# Descriptors (by Mordred name) that the pretrained AqSolPred models expect,
# in order. Shared by both the SMILES-based (web.app) and Mol-based
# (cli.report, via main.calculate_logS) descriptor-generation entry points.

SELECTED_COLUMNS: list[str] = [
    "nHBAcc",
    "nHBDon",
    "nRot",
    "nBonds",
    "nAromBond",
    "nBondsO",
    "nBondsS",
    "TopoPSA(NO)",
    "TopoPSA",
    "LabuteASA",
    "bpol",
    "nAcid",
    "nBase",
    "ECIndex",
    "GGI1",
    "SLogP",
    "SMR",
    "BertzCT",
    "BalabanJ",
    "Zagreb1",
    "ABCGG",
    "nHRing",
    "naHRing",
    "NsCH3",
    "NaaCH",
    "NaaaC",
    "NssssC",
    "SsCH3",
    "SdCH2",
    "SssCH2",
    "StCH",
    "SdsCH",
    "SaaCH",
    "SsssCH",
    "SdssC",
    "SaasC",
    "SaaaC",
    "SsNH2",
    "SssNH",
    "StN",
    "SdsN",
    "SaaN",
    "SsssN",
    "SaasN",
    "SsOH",
    "SdO",
    "SssO",
    "SaaO",
    "SsF",
    "SdsssP",
    "SsSH",
    "SdS",
    "SddssS",
    "SsCl",
    "SsI",
]
